# WB1 - Data Cleaning 
------

In [16]:
# importing packages
#############################
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import csv

import plotly.graph_objects as go
#import sweetviz

#pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

---
The initial Workbook (WB1) cover the basic data cleaning steps required to perform the outlined analysis - Please refer to the report for deatils. As an outcome cleaned datasets for the descriptive and supply/demand analysis as well as consecutive predictive analysis are created and stored.

---

In [17]:
#load data

############################# Kaggle #############################
#load questions only
df_qs = pd.read_csv('/project/DATA/Kaggle_Survey/questions_only.csv')
print(df_qs.shape)

#survey schema
df_ss = pd.read_csv('/project/DATA/Kaggle_Survey/survey_schema.csv')
print(df_ss.shape)

#multiple choise responses
df_mc = pd.read_csv('/project/DATA/Kaggle_Survey/multiple_choice_responses.csv')
print(df_mc.shape)

#other/free text responses
df_tr = pd.read_csv('/project/DATA/Kaggle_Survey/other_text_responses.csv')
print(df_tr.shape)

(1, 35)
(10, 35)
(19718, 246)
(19718, 28)

/opt/anaconda/envs/Python3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning:

Columns (0,3,7,19,34,47,49,50,51,52,53,54,68,81,94,96,109,115,130,139,147,154,167,180,193,206,219,232,245) have mixed types.Specify dtype option on import or set low_memory=False.

---
Kaggle conducted an annual survey within its community to obtain a comprehensive view of the state of machine learning and data science for 2019. In total 19,717 responses from 171 countries and territories were recorded over the three-week timeframe in which the participants had access to the survey. It covers sociographic, geographic, employment and technology insights which form the basis of this study.

---

In [18]:
#kaggle data transofrmation
#############################

#combine all answers (multiple choice and text responses)
print(df_mc.shape)
print(df_tr.shape)

#df_an = pd.concat([df_mc, df_tr], axis=1)
df_an = df_mc.copy()
df_an = df_an.iloc[1:,:]
print(df_an.shape)

(19718, 246)
(19718, 28)
(19717, 246)

In [19]:
#basic insights
df_an.head(1)

,Time from Start to Finish (seconds),Q1,Q2,Q2_OTHER_TEXT,Q3,Q4,Q5,Q5_OTHER_TEXT,Q6,Q7,Q8,Q9_Part_1,Q9_Part_2,Q9_Part_3,Q9_Part_4,Q9_Part_5,Q9_Part_6,Q9_Part_7,Q9_Part_8,Q9_OTHER_TEXT,Q10,Q11,Q12_Part_1,Q12_Part_2,Q12_Part_3,Q12_Part_4,Q12_Part_5,Q12_Part_6,Q12_Part_7,Q12_Part_8,Q12_Part_9,Q12_Part_10,Q12_Part_11,Q12_Part_12,Q12_OTHER_TEXT,Q13_Part_1,Q13_Part_2,Q13_Part_3,Q13_Part_4,Q13_Part_5,Q13_Part_6,Q13_Part_7,Q13_Part_8,Q13_Part_9,Q13_Part_10,Q13_Part_11,Q13_Part_12,Q13_OTHER_TEXT,Q14,Q14_Part_1_TEXT,Q14_Part_2_TEXT,Q14_Part_3_TEXT,Q14_Part_4_TEXT,Q14_Part_5_TEXT,Q14_OTHER_TEXT,Q15,Q16_Part_1,Q16_Part_2,Q16_Part_3,Q16_Part_4,Q16_Part_5,Q16_Part_6,Q16_Part_7,Q16_Part_8,Q16_Part_9,Q16_Part_10,Q16_Part_11,Q16_Part_12,Q16_OTHER_TEXT,Q17_Part_1,Q17_Part_2,Q17_Part_3,Q17_Part_4,Q17_Part_5,Q17_Part_6,Q17_Part_7,Q17_Part_8,Q17_Part_9,Q17_Part_10,Q17_Part_11,Q17_Part_12,Q17_OTHER_TEXT,Q18_Part_1,Q18_Part_2,Q18_Part_3,Q18_Part_4,Q18_Part_5,Q18_Part_6,Q18_Part_7,Q18_Part_8,Q18_Part_9,Q18_Part_10,Q18_Part_11,Q18_Part_12,Q18_OTHER_TEXT,Q19,Q19_OTHER_TEXT,Q20_Part_1,Q20_Part_2,Q20_Part_3,Q20_Part_4,Q20_Part_5,Q20_Part_6,Q20_Part_7,Q20_Part_8,Q20_Part_9,Q20_Part_10,Q20_Part_11,Q20_Part_12,Q20_OTHER_TEXT,Q21_Part_1,Q21_Part_2,Q21_Part_3,Q21_Part_4,Q21_Part_5,Q21_OTHER_TEXT,Q22,Q23,Q24_Part_1,Q24_Part_2,Q24_Part_3,Q24_Part_4,Q24_Part_5,Q24_Part_6,Q24_Part_7,Q24_Part_8,Q24_Part_9,Q24_Part_10,Q24_Part_11,Q24_Part_12,Q24_OTHER_TEXT,Q25_Part_1,Q25_Part_2,Q25_Part_3,Q25_Part_4,Q25_Part_5,Q25_Part_6,Q25_Part_7,Q25_Part_8,Q25_OTHER_TEXT,Q26_Part_1,Q26_Part_2,Q26_Part_3,Q26_Part_4,Q26_Part_5,Q26_Part_6,Q26_Part_7,Q26_OTHER_TEXT,Q27_Part_1,Q27_Part_2,Q27_Part_3,Q27_Part_4,Q27_Part_5,Q27_Part_6,Q27_OTHER_TEXT,Q28_Part_1,Q28_Part_2,Q28_Part_3,Q28_Part_4,Q28_Part_5,Q28_Part_6,Q28_Part_7,Q28_Part_8,Q28_Part_9,Q28_Part_10,Q28_Part_11,Q28_Part_12,Q28_OTHER_TEXT,Q29_Part_1,Q29_Part_2,Q29_Part_3,Q29_Part_4,Q29_Part_5,Q29_Part_6,Q29_Part_7,Q29_Part_8,Q29_Part_9,Q29_Part_10,Q29_Part_11,Q29_Part_12,Q29_OTHER_TEXT,Q30_Part_1,Q30_Part_2,Q30_Part_3,Q30_Part_4,Q30_Part_5,Q30_Part_6,Q30_Part_7,Q30_Part_8,Q30_Part_9,Q30_Part_10,Q30_Part_11,Q30_Part_12,Q30_OTHER_TEXT,Q31_Part_1,Q31_Part_2,Q31_Part_3,Q31_Part_4,Q31_Part_5,Q31_Part_6,Q31_Part_7,Q31_Part_8,Q31_Part_9,Q31_Part_10,Q31_Part_11,Q31_Part_12,Q31_OTHER_TEXT,Q32_Part_1,Q32_Part_2,Q32_Part_3,Q32_Part_4,Q32_Part_5,Q32_Part_6,Q32_Part_7,Q32_Part_8,Q32_Part_9,Q32_Part_10,Q32_Part_11,Q32_Part_12,Q32_OTHER_TEXT,Q33_Part_1,Q33_Part_2,Q33_Part_3,Q33_Part_4,Q33_Part_5,Q33_Part_6,Q33_Part_7,Q33_Part_8,Q33_Part_9,Q33_Part_10,Q33_Part_11,Q33_Part_12,Q33_OTHER_TEXT,Q34_Part_1,Q34_Part_2,Q34_Part_3,Q34_Part_4,Q34_Part_5,Q34_Part_6,Q34_Part_7,Q34_Part_8,Q34_Part_9,Q34_Part_10,Q34_Part_11,Q34_Part_12,Q34_OTHER_TEXT
1,510,22-24,Male,-1,France,Master’s degree,Software Engineer,-1,"1000-9,999 employees",0,I do not know,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1,"30,000-39,999",$0 (USD),Twitter (data science influencers),NaN,NaN,"Kaggle (forums, blog, social media, etc)",NaN,NaN,NaN,"Blogs (Towards Data Science, Medium, Analytics Vidhya, KDnuggets etc)","Journal Publications (traditional publications, preprint journals, etc)",NaN,NaN,NaN,-1,NaN,Coursera,NaN,DataCamp,NaN,Kaggle Courses (i.e. Kaggle Learn),NaN,Udemy,NaN,NaN,NaN,NaN,-1,"Basic statistical software (Microsoft Excel, Google Sheets, etc.)",0,-1,-1,-1,-1,-1,1-2 years,"Jupyter (JupyterLab, Jupyter Notebooks, etc)",RStudio,PyCharm,NaN,MATLAB,NaN,Spyder,NaN,NaN,NaN,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,-1,Python,R,SQL,NaN,NaN,Java,Javascript,NaN,NaN,MATLAB,NaN,NaN,-1,Python,-1,NaN,Matplotlib,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1,CPUs,GPUs,NaN,NaN,NaN,-1,Never,1-2 years,Linear or Logistic Regression,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1

---
Please see below an overvie (df_qs) of all 34 questions covered within the survey. These questions lead to multiple (dummy variable) columns for provided answers (see df_mc/df_an).

---

In [20]:
#full excerpt of questions
pd.set_option('display.max_colwidth', -1)
df_qs

/opt/anaconda/envs/Python3/lib/python3.6/site-packages/ipykernel/__main__.py:2: FutureWarning:

Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.

,Time from Start to Finish (seconds),Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,Q16,Q17,Q18,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27,Q28,Q29,Q30,Q31,Q32,Q33,Q34
0,Duration (in seconds),What is your age (# years)?,What is your gender? - Selected Choice,In which country do you currently reside?,What is the highest level of formal education that you have attained or plan to attain within the next 2 years?,Select the title most similar to your current role (or most recent title if retired): - Selected Choice,What is the size of the company where you are employed?,Approximately how many individuals are responsible for data science workloads at your place of business?,Does your current employer incorporate machine learning methods into their business?,Select any activities that make up an important part of your role at work: (Select all that apply) - Selected Choice,What is your current yearly compensation (approximate $USD)?,Approximately how much money have you spent on machine learning and/or cloud computing products at your work in the past 5 years?,Who/what are your favorite media sources that report on data science topics? (Select all that apply) - Selected Choice,On which platforms have you begun or completed data science courses? (Select all that apply) - Selected Choice,What is the primary tool that you use at work or school to analyze data? (Include text response) - Selected Choice,How long have you been writing code to analyze data (at work or at school)?,Which of the following integrated development environments (IDE's) do you use on a regular basis? (Select all that apply) - Selected Choice,Which of the following hosted notebook products do you use on a regular basis? (Select all that apply) - Selected Choice,What programming languages do you use on a regular basis? (Select all that apply) - Selected Choice,What programming language would you recommend an aspiring data scientist to learn first? - Selected Choice,What data visualization libraries or tools do you use on a regular basis? (Select all that apply) - Selected Choice,Which types of specialized hardware do you use on a regular basis? (Select all that apply) - Selected Choice,Have you ever used a TPU (tensor processing unit)?,For how many years have you used machine learning methods?,Which of the following ML algorithms do you use on a regular basis? (Select all that apply): - Selected Choice,Which categories of ML tools do you use on a regular basis? (Select all that apply) - Selected Choice,Which categories of computer vision methods do you use on a regular basis? (Select all that apply) - Selected Choice,Which of the following natural language processing (NLP) methods do you use on a regular basis? (Select all that apply) - Selected Choice,Which of the following machine learning frameworks do you use on a regular basis? (Select all that apply) - Selected Choice,Which of the following cloud computing platforms do you use on a regular basis? (Select all that apply) - Selected Choice,Which specific cloud computing products do you use on a regular basis? (Select all that apply) - Selected Choice,Which specific big data / analytics products do you use on a regular basis? (Select all that apply) - Selected Choice,Which of the following machine learning products do you use on a regular basis? (Select all that apply) - Selected Choice,Which automated machine learning tools (or partial AutoML tools) do you use on a regular basis? (Select all that apply) - Selected Choice,Which of the following relational database products do you use on a regular basis? (Select all that apply) - Selected Choice

In [21]:
df_an.dtypes

Time from Start to Finish (seconds)    object
Q1                                     object
Q2                                     object
Q2_OTHER_TEXT                          object
Q3                                     object
                                        ...
Q34_Part_9                             object
Q34_Part_10                            object
Q34_Part_11                            object
Q34_Part_12                            object
Q34_OTHER_TEXT                         object
Length: 246, dtype: object

In [22]:
df_an.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19717 entries, 1 to 19717
Columns: 246 entries, Time from Start to Finish (seconds) to Q34_OTHER_TEXT
dtypes: object(246)
memory usage: 37.0+ MB

---
The author of the analysis decided to validate answers based on the required time of responses. In detail, answers quicker than 3min and longer than 2hours are excluded.

---

In [23]:
#kaggle initial data cleaning
####################################################

#transform reposnse time to numeric value
df_an['Time from Start to Finish (seconds)'] = pd.to_numeric(df_an['Time from Start to Finish (seconds)'])
df_an_num_res = len(df_an.index)

#spend less than 3min OR more than 2hours
df_an = df_an[df_an['Time from Start to Finish (seconds)']>180] #3min * 60sec = 180
df_an = df_an[df_an['Time from Start to Finish (seconds)']<7200] #2h * 60min * 60sec = 7200
df_an_num_res_new = df_an_num_res - len(df_an.index)

df_an['valid_response'] = 1

#outout
print('Number of excluded datapoints: ',df_an_num_res_new)
print('New data frame shape: ',df_an.shape)

Number of excluded datapoints:  3728
New data frame shape:  (15989, 247)

---
Next, the job titles had to be standardtized for the following analysis; also important for later comparison between Kaggle and Glassdoor data.

-------

In [24]:
#treat positions/ job levels
####################################################

df_an['Q5'] = df_an['Q5'].fillna('Other')

#drop students, others and non employed
df_an = df_an[df_an['Q5']!='Student']
df_an = df_an[df_an['Q5']!='Other']
df_an = df_an[df_an['Q5']!='Not employed']

#Business/Data Analyst
df_an.Q5[df_an['Q5']=='Business Analyst'] = 'Business/Data Analyst'
df_an.Q5[df_an['Q5']=='Data Analyst'] = 'Business/Data Analyst'

#Researcher
df_an.Q5[df_an['Q5']=='Research Scientist'] = 'Researcher'
df_an.Q5[df_an['Q5']=='Statistician'] = 'Researcher'

#Data/Software Engineer
df_an.Q5[df_an['Q5']=='Data Engineer'] = 'Data/Software Engineer'
df_an.Q5[df_an['Q5']=='Software Engineer'] = 'Data/Software Engineer'

print(df_an.groupby(df_an['Q5']).mean())
print(df_an.shape)

                         Time from Start to Finish (seconds)  valid_response
Q5
Business/Data Analyst    840.743077                           1.0
DBA/Database Engineer    879.863636                           1.0
Data Scientist           901.839405                           1.0
Data/Software Engineer   889.524928                           1.0
Product/Project Manager  923.003263                           1.0
Researcher               901.102740                           1.0
(10354, 247)

/opt/anaconda/envs/Python3/lib/python3.6/site-packages/ipykernel/__main__.py:13: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/opt/anaconda/envs/Python3/lib/python3.6/site-packages/ipykernel/__main__.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/opt/anaconda/envs/Python3/lib/python3.6/site-packages/ipykernel/__main__.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/opt/anaconda/envs/Python3/lib/python3.6/site-packages/ipykernel/__main__.py:20: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/opt/anaconda/envs/Python3/lib/python3.6/site-packages/ipykernel/__main__.py:21: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [25]:
#export csv for seperate visualization workbook
###################################

df_an.to_csv(r'/project/DATA/Kaggle_Survey/Data_Cleaning/CLEANED_valid_responses.csv', index=False)

###################################

---
Data cleaning commenced with the preperation for predictive modelling. Besides others this included target variable engineering, creating dummy variables, treating data anomalies and normalizing data. Please see the below code section for details.


---

In [26]:
#copy previous data frame to new predictive dataframe
df_pred = df_an.copy()

#output
print(df_pred.shape)
df_pred.head(1)

(10354, 247)

,Time from Start to Finish (seconds),Q1,Q2,Q2_OTHER_TEXT,Q3,Q4,Q5,Q5_OTHER_TEXT,Q6,Q7,Q8,Q9_Part_1,Q9_Part_2,Q9_Part_3,Q9_Part_4,Q9_Part_5,Q9_Part_6,Q9_Part_7,Q9_Part_8,Q9_OTHER_TEXT,Q10,Q11,Q12_Part_1,Q12_Part_2,Q12_Part_3,Q12_Part_4,Q12_Part_5,Q12_Part_6,Q12_Part_7,Q12_Part_8,Q12_Part_9,Q12_Part_10,Q12_Part_11,Q12_Part_12,Q12_OTHER_TEXT,Q13_Part_1,Q13_Part_2,Q13_Part_3,Q13_Part_4,Q13_Part_5,Q13_Part_6,Q13_Part_7,Q13_Part_8,Q13_Part_9,Q13_Part_10,Q13_Part_11,Q13_Part_12,Q13_OTHER_TEXT,Q14,Q14_Part_1_TEXT,Q14_Part_2_TEXT,Q14_Part_3_TEXT,Q14_Part_4_TEXT,Q14_Part_5_TEXT,Q14_OTHER_TEXT,Q15,Q16_Part_1,Q16_Part_2,Q16_Part_3,Q16_Part_4,Q16_Part_5,Q16_Part_6,Q16_Part_7,Q16_Part_8,Q16_Part_9,Q16_Part_10,Q16_Part_11,Q16_Part_12,Q16_OTHER_TEXT,Q17_Part_1,Q17_Part_2,Q17_Part_3,Q17_Part_4,Q17_Part_5,Q17_Part_6,Q17_Part_7,Q17_Part_8,Q17_Part_9,Q17_Part_10,Q17_Part_11,Q17_Part_12,Q17_OTHER_TEXT,Q18_Part_1,Q18_Part_2,Q18_Part_3,Q18_Part_4,Q18_Part_5,Q18_Part_6,Q18_Part_7,Q18_Part_8,Q18_Part_9,Q18_Part_10,Q18_Part_11,Q18_Part_12,Q18_OTHER_TEXT,Q19,Q19_OTHER_TEXT,Q20_Part_1,Q20_Part_2,Q20_Part_3,Q20_Part_4,Q20_Part_5,Q20_Part_6,Q20_Part_7,Q20_Part_8,Q20_Part_9,Q20_Part_10,Q20_Part_11,Q20_Part_12,Q20_OTHER_TEXT,Q21_Part_1,Q21_Part_2,Q21_Part_3,Q21_Part_4,Q21_Part_5,Q21_OTHER_TEXT,Q22,Q23,Q24_Part_1,Q24_Part_2,Q24_Part_3,Q24_Part_4,Q24_Part_5,Q24_Part_6,Q24_Part_7,Q24_Part_8,Q24_Part_9,Q24_Part_10,Q24_Part_11,Q24_Part_12,Q24_OTHER_TEXT,Q25_Part_1,Q25_Part_2,Q25_Part_3,Q25_Part_4,Q25_Part_5,Q25_Part_6,Q25_Part_7,Q25_Part_8,Q25_OTHER_TEXT,Q26_Part_1,Q26_Part_2,Q26_Part_3,Q26_Part_4,Q26_Part_5,Q26_Part_6,Q26_Part_7,Q26_OTHER_TEXT,Q27_Part_1,Q27_Part_2,Q27_Part_3,Q27_Part_4,Q27_Part_5,Q27_Part_6,Q27_OTHER_TEXT,Q28_Part_1,Q28_Part_2,Q28_Part_3,Q28_Part_4,Q28_Part_5,Q28_Part_6,Q28_Part_7,Q28_Part_8,Q28_Part_9,Q28_Part_10,Q28_Part_11,Q28_Part_12,Q28_OTHER_TEXT,Q29_Part_1,Q29_Part_2,Q29_Part_3,Q29_Part_4,Q29_Part_5,Q29_Part_6,Q29_Part_7,Q29_Part_8,Q29_Part_9,Q29_Part_10,Q29_Part_11,Q29_Part_12,Q29_OTHER_TEXT,Q30_Part_1,Q30_Part_2,Q30_Part_3,Q30_Part_4,Q30_Part_5,Q30_Part_6,Q30_Part_7,Q30_Part_8,Q30_Part_9,Q30_Part_10,Q30_Part_11,Q30_Part_12,Q30_OTHER_TEXT,Q31_Part_1,Q31_Part_2,Q31_Part_3,Q31_Part_4,Q31_Part_5,Q31_Part_6,Q31_Part_7,Q31_Part_8,Q31_Part_9,Q31_Part_10,Q31_Part_11,Q31_Part_12,Q31_OTHER_TEXT,Q32_Part_1,Q32_Part_2,Q32_Part_3,Q32_Part_4,Q32_Part_5,Q32_Part_6,Q32_Part_7,Q32_Part_8,Q32_Part_9,Q32_Part_10,Q32_Part_11,Q32_Part_12,Q32_OTHER_TEXT,Q33_Part_1,Q33_Part_2,Q33_Part_3,Q33_Part_4,Q33_Part_5,Q33_Part_6,Q33_Part_7,Q33_Part_8,Q33_Part_9,Q33_Part_10,Q33_Part_11,Q33_Part_12,Q33_OTHER_TEXT,Q34_Part_1,Q34_Part_2,Q34_Part_3,Q34_Part_4,Q34_Part_5,Q34_Part_6,Q34_Part_7,Q34_Part_8,Q34_Part_9,Q34_Part_10,Q34_Part_11,Q34_Part_12,Q34_OTHER_TEXT,valid_response
1,510,22-24,Male,-1,France,Master’s degree,Data/Software Engineer,-1,"1000-9,999 employees",0,I do not know,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1,"30,000-39,999",$0 (USD),Twitter (data science influencers),NaN,NaN,"Kaggle (forums, blog, social media, etc)",NaN,NaN,NaN,"Blogs (Towards Data Science, Medium, Analytics Vidhya, KDnuggets etc)","Journal Publications (traditional publications, preprint journals, etc)",NaN,NaN,NaN,-1,NaN,Coursera,NaN,DataCamp,NaN,Kaggle Courses (i.e. Kaggle Learn),NaN,Udemy,NaN,NaN,NaN,NaN,-1,"Basic statistical software (Microsoft Excel, Google Sheets, etc.)",0,-1,-1,-1,-1,-1,1-2 years,"Jupyter (JupyterLab, Jupyter Notebooks, etc)",RStudio,PyCharm,NaN,MATLAB,NaN,Spyder,NaN,NaN,NaN,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,-1,Python,R,SQL,NaN,NaN,Java,Javascript,NaN,NaN,MATLAB,NaN,NaN,-1,Python,-1,NaN,Matplotlib,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1,CPUs,GPUs,NaN,NaN,NaN,-1,Never,1-2 years,Linear or Logistic Regression,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1,1

In [27]:
#target variabel engineering 
#############################

#rework target variable (Q10) by formatting string data
comp = df_pred.Q10.str.replace(',', '').str.replace('500000\+', '500000-500000').str.replace('$', '').str.split('-')
df_pred['yearly_comp_combined'] = comp

#split single string column in to bottom and top value column
marker = df_pred['yearly_comp_combined'].apply(pd.Series)
marker = marker.rename(columns = lambda x : 'mark_' + str(x))
marker.dropna(inplace=True)

#set types to numerical and form average of both bottom and top end data per instance
marker['mark_0'] = marker['mark_0'].astype(int)
marker['mark_1'] = marker['mark_1'].astype(int)
marker['result'] = (marker['mark_0']+marker['mark_1'])/2 #average of both marker 1 and 2

#include compensation in target variable format
df_pred['yearly_comp_numerical'] = marker['result'] #set yearly compensation to previously engineered values
df_pred['yearly_comp_numerical'] = df_pred['yearly_comp_numerical'].fillna(0)
df_pred = df_pred.drop('yearly_comp_combined', axis = 1)

#drop rows with compensation = 0
#print(df_pred.shape)
#df_pred = df_pred[df_pred['yearly_comp_numerical']!=0]

#output
print(df_pred.shape)
df_pred[['Q10', 'yearly_comp_numerical']].head(3)

(10354, 248)

             Q10  yearly_comp_numerical
1  30,000-39,999  34999.5
2  5,000-7,499    6249.5
6  60,000-69,999  64999.5

In [28]:
#data compensation validation (removing responses with error in compensation data field)
#########################

indexNames_BA = df_pred.loc[((df_pred['Q5']=='Data Scientist')&(df_pred['yearly_comp_numerical']<=2500)),:].index
df_pred.drop(indexNames_BA , inplace=True)

indexNames_DS = df_pred.loc[((df_pred['Q5']=='Data Scientist')&(df_pred['yearly_comp_numerical']<=2500)),:].index
df_pred.drop(indexNames_DS , inplace=True)

indexNames_SE = df_pred.loc[((df_pred['Q5']=='Data/Software Engineer')&(df_pred['yearly_comp_numerical']<=2500)),:].index
df_pred.drop(indexNames_SE , inplace=True)

indexNames_PM = df_pred.loc[((df_pred['Q5']=='Data/Software Engineer')&(df_pred['yearly_comp_numerical']<=2500)),:].index
df_pred.drop(indexNames_PM , inplace=True)

indexNames_RS = df_pred.loc[((df_pred['Q5']=='Data/Software Engineer')&(df_pred['yearly_comp_numerical']<=2500)),:].index
df_pred.drop(indexNames_RS , inplace=True)

#output
print(df_pred.shape)

(8942, 248)

In [29]:
#export csv for seperate prediction workbook
###################################

df_pred.to_csv(r'/project/DATA/Kaggle_Survey/Data_Cleaning/CLEANED_prediction.csv', index=False)

###################################

In [30]:
#compensation by profession
###################################
print(df_pred['yearly_comp_numerical'].mean())
df_pred.groupby(df_pred['Q5'])['yearly_comp_numerical'].mean()

53610.50827555357

Q5
Business/Data Analyst      34674.142051
DBA/Database Engineer      47323.390152
Data Scientist             71292.753043
Data/Software Engineer     53372.335742
Product/Project Manager    61497.482055
Researcher                 43664.603767
Name: yearly_comp_numerical, dtype: float64

In [31]:
df_pred.columns

Index(['Time from Start to Finish (seconds)', 'Q1', 'Q2', 'Q2_OTHER_TEXT', 'Q3', 'Q4', 'Q5', 'Q5_OTHER_TEXT', 'Q6', 'Q7',
       ...
       'Q34_Part_6', 'Q34_Part_7', 'Q34_Part_8', 'Q34_Part_9', 'Q34_Part_10', 'Q34_Part_11', 'Q34_Part_12', 'Q34_OTHER_TEXT', 'valid_response', 'yearly_comp_numerical'], dtype='object', length=248)

---